### ISSUE TITLE
When arming or disarming via SIRI, Siri reports it could not arm or disarm

### ISSUE THREAD

**Issue by Lotusshaney** [jak1502/homebridge-yalesmarthomealarm#4]
When arming or disarming via SIRI, Siri reports it could not arm or disarm the alarm but is actually successful in doing both commands.

**Comment by jak1502** [comment]
I have the same behaviour. When I wrote the plugin I tried to work out why this was but gave up. I think it might be that Siri isn't waiting to check the status, and as the alarm takes some time to set it gets confused. I will see if I can fix it next time I have some spare time.

**Comment by p0sixturtle** [comment]
I have a Yale doorlock in my yale alarm system. Would it be possible to add this as well?

**Comment by davidwhicker** [comment]
There are a few other yalealarm homebridge plugs that have siri reporting correctly so its possible. Perhaps take a look at their code? 

 Their plugins have broken on the latest Hoobs update so I am happy with yours but it would be nice for Siri to report correctly.

**Comment by jak1502** [comment]
Hi David. 

I will take a look at it, there is also a couple of updates that are needed.

**Comment by davidwhicker** [comment]
Brilliant, thank you. 

If it helps on the latest Hoobs update the error that now appears on the Johnathan Dann Yale plugin is:

02/05/2020, 08:05:12 [Burglar Alarm] Initializing YaleSyncAlarm platform...
02/05/2020, 08:05:12 Error: Cannot update reachability on non-bridged accessory!
at Accessory._this.updateReachability (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:259:23)
at Platform.updateReachability (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/platform.js:88:37)
at YaleSyncPlatform.configurePanel (/home/hoobs/.hoobs/node_modules/homebridge-yalesyncalarm/dist/YaleSyncPlatform.js:382:23)
at YaleSyncPlatform.configureAccessory (/home/hoobs/.hoobs/node_modules/homebridge-yalesyncalarm/dist/YaleSyncPlatform.js:235:22)
at Server.configCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:332:26)
at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:95:14)
at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
at Object. (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
at Module._compile (internal/modules/cjs/loader.js:1156:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)

**Comment by jak1502** [comment]
I’ve had a quick look at this and still can’t see why it’s still not working. So I’m going to have a go at rewriting it over the next few days. Once it’s ready I will let you know as I could do with a tester.

**Comment by davidwhicker** [comment]
Hi Jak

Of course no problem at all, I would be happy to test it.

I must say that your system is much faster ( on the updating when launching Home app ) than the other Yale plugin so hats off to you on that part.

Kind regards

David Whicker

**Comment by davidwhicker** [comment]
Hi

Not sure if this will help. 

https://github.com/homebridge/homebridge-plugin-template

**Comment by davidwhicker** [comment]
New error popping up on logs:

[5/11/2020, 10:54:22] [Alarm] FetchError: request to https://mob.yalehomesystem.co.uk/yapi/o/token/ failed, reason: getaddrinfo EAI_AGAIN mob.yalehomesystem.co.uk
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-yalesmarthomealarm/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}

**Comment by davidwhicker** [comment]
Hi. I just wondered how this was going? Thank you
